apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: mrudulsmohan/zomato-react:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

